-- MySQL Script generated by MySQL Workbench
-- Mon Sep 12 22:22:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema online_stores_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema online_stores_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `online_stores_db` DEFAULT CHARACTER SET utf8 ;
USE `online_stores_db` ;

-- -----------------------------------------------------
-- Table `online_stores_db`.`online_stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`online_stores` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(50) NOT NULL,
  `bestseller` VARCHAR(50) NOT NULL,
  `sale` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`authors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `country` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`admins` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `online_store_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `salary` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_admins_online_stores1_idx` (`online_store_id` ASC) VISIBLE,
  CONSTRAINT `fk_admins_online_stores1`
    FOREIGN KEY (`online_store_id`)
    REFERENCES `online_stores_db`.`online_stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`customers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`cards` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `number` INT NOT NULL,
  `validity_period` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  INDEX `fk_cards_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_cards_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `online_stores_db`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`shopping_carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`shopping_carts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `online_store_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shopping_carts_online_stores1_idx` (`online_store_id` ASC) VISIBLE,
  INDEX `fk_shopping_carts_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_shopping_carts_online_stores1`
    FOREIGN KEY (`online_store_id`)
    REFERENCES `online_stores_db`.`online_stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shopping_carts_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `online_stores_db`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`publishing_houses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`publishing_houses` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`books`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`books` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `author_id` BIGINT UNSIGNED NOT NULL,
  `shopping_cart_id` BIGINT UNSIGNED NOT NULL,
  `online_store_id` BIGINT UNSIGNED NOT NULL,
  `publishing_house_id` BIGINT UNSIGNED NOT NULL,
  `title` VARCHAR(60) NOT NULL,
  `genre` VARCHAR(60) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_books_authors1_idx` (`author_id` ASC) VISIBLE,
  INDEX `fk_books_shopping_carts1_idx` (`shopping_cart_id` ASC) VISIBLE,
  INDEX `fk_books_online_stores1_idx` (`online_store_id` ASC) VISIBLE,
  INDEX `fk_books_publishing_houses1_idx` (`publishing_house_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_authors1`
    FOREIGN KEY (`author_id`)
    REFERENCES `online_stores_db`.`authors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_shopping_carts1`
    FOREIGN KEY (`shopping_cart_id`)
    REFERENCES `online_stores_db`.`shopping_carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_online_stores1`
    FOREIGN KEY (`online_store_id`)
    REFERENCES `online_stores_db`.`online_stores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_books_publishing_houses1`
    FOREIGN KEY (`publishing_house_id`)
    REFERENCES `online_stores_db`.`publishing_houses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`online_store_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`online_store_customers` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `online_store_id` BIGINT UNSIGNED NOT NULL,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_online_stores_has_customers_customers1_idx` (`customer_id` ASC) VISIBLE,
  INDEX `fk_online_stores_has_customers_online_stores1_idx` (`online_store_id` ASC) VISIBLE,
  CONSTRAINT `fk_online_stores_has_customers_online_stores1`
    FOREIGN KEY (`online_store_id`)
    REFERENCES `online_stores_db`.`online_stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_online_stores_has_customers_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `online_stores_db`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `online_stores_db`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `online_stores_db`.`contacts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` BIGINT UNSIGNED NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `phone_number` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `fk_contacts_customers1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_customers1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `online_stores_db`.`customers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
